[package]
name = "cljrs-stdlib"
version = "0.1.250"
edition = "2024"
description = "Built-in standard library namespaces for clojurust (clojure.string, clojure.set, clojure.test, …)"
license.workspace = true
repository.workspace = true

[features]
default = []
no-gc = ["cljrs-gc/no-gc", "cljrs-value/no-gc", "cljrs-runtime/no-gc"]

[dependencies]
cljrs-gc      = { workspace = true }
cljrs-ir      = { workspace = true }
cljrs-value   = { workspace = true }
cljrs-runtime = { workspace = true }
cljrs-reader  = { workspace = true }

