//! Golden record of what every `^meta` annotation does, in every position, in
//! every tier.
//!
//! The example tests say what specific cases must do and the property tests say
//! what laws must hold. This says what the implementation *currently does*, for
//! the whole matrix, byte for byte — so a change nobody intended shows up as a
//! diff in review instead of being absorbed silently.
//!
//! That is the open/closed line for this behaviour: extending it appends rows,
//! and any edit to an existing row has to be argued for in the diff. A row is
//! not a specification — several of them record a deliberate divergence from
//! the JVM (noted in the file header) — it is a record.
//!
//! Regenerate after an intentional change:
//!
//! ```sh
//! UPDATE_GOLDEN=1 cargo test -p cljrs-runtime --test meta_golden
//! ```

use cljrs_reader::Parser;
use cljrs_runtime::env::env::Env;
use cljrs_value::Value;

mod common;
use common::reset_env_in;

/// The namespace every row runs in. It is the same name each time and emptied
/// between rows: `::kw` resolves against the current namespace, so the name is
/// part of the recorded answer and must not drift. `user` specifically, because
/// that is the name the golden file already records and a rename would rewrite
/// every `::kw` row for no behavioural reason.
const NS: &str = "user";

fn make_env(
    mode: cljrs_runtime::ExecutionMode,
) -> (std::sync::Arc<cljrs_runtime::env::env::GlobalEnv>, Env) {
    reset_env_in(mode, NS)
}

const GOLDEN: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/golden/reader_metadata.txt"
);

/// The answer, or the message of the error — never a span or a debug dump,
/// which would make the golden file churn on unrelated edits.
fn outcome(env: &mut Env, src: &str) -> String {
    let mut parser = Parser::new(src.to_string(), "<golden>".to_string());
    let forms = match parser.parse_all() {
        Ok(forms) => forms,
        Err(_) => return "READ-ERROR".to_string(),
    };
    let mut result = Value::Nil;
    for form in forms {
        match cljrs_runtime::tiered::eval(&form, env) {
            Ok(v) => result = v,
            Err(e) => {
                let text = format!("{e:?}").replace('\n', " ");
                // Prefer the human message; fall back to the first quoted
                // string, then to the whole debug rendering.
                let msg = text
                    .split("message: \"")
                    .nth(1)
                    .and_then(|s| s.split('"').next())
                    .or_else(|| text.split('"').nth(1))
                    .map(str::to_string)
                    .unwrap_or(text);
                return format!("ERROR {msg}");
            }
        }
    }
    format!("{result}")
}

/// Annotations, written without the leading `^`.
const ANNOTATIONS: &[&str] = &[
    ":kw",
    ":async",
    "::kw",
    "Sym",
    "ns.q/Sym",
    "\"Str\"",
    "{:a 1}",
    "{:a (+ 1 2)}",
    "{:tag 'String}",
    "nil",
    "42",
];

/// Annotated forms, one per shape the attach rule distinguishes.
const FORMS: &[&str] = &[
    "[1 2]",
    "()",
    "{:k 1}",
    "#{1}",
    "(fn [] 1)",
    "#(inc %)",
    "(list 1)",
    "(vector 1)",
    "(if true [1] [2])",
    "(do [1])",
    "'(1 2)",
    "'sym",
    "42",
    "\"s\"",
    ":kw",
    "nil",
];

fn render() -> String {
    let mut out = String::new();
    out.push_str(
        "# Reader metadata — golden behaviour matrix\n\
         #\n\
         # Generated by tests/meta_golden.rs. Regenerate with:\n\
         #   UPDATE_GOLDEN=1 cargo test -p cljrs-runtime --test meta_golden\n\
         #\n\
         # Columns: <position> | <expression> => <(meta …) of it>\n\
         #\n\
         # Positions:\n\
         #   quoted     '^A F   — the annotation is data; it lands on anything IObj\n\
         #   evaluated   ^A F   — it lands only on a form that constructs an IObj\n\
         #   syntaxq    `^A F   — data, like quoted, but gensyms/unquotes resolve\n\
         #\n\
         # Deliberate divergences from Clojure 1.12, measured against it:\n\
         #   - the JVM reader REJECTS `^42 F` at read time; here it is a runtime\n\
         #     error, so the message is recorded rather than READ-ERROR.\n\
         #   - the JVM reader rejects `^{:a 1} 42` (metadata on a non-IMeta\n\
         #     literal); here the annotation is dropped, matching the treatment\n\
         #     of every other value that cannot carry metadata.\n\
         #   - `'^{:a 1} 'sym` keeps the annotation as data; the JVM tracks\n\
         #     source line/column metadata that this runtime does not carry.\n\n",
    );

    for &position in &["quoted", "evaluated", "syntaxq"] {
        out.push_str(&format!("## {position}\n\n"));
        for &ann in ANNOTATIONS {
            for &form in FORMS {
                let expr = match position {
                    "quoted" => format!("'^{ann} {form}"),
                    "evaluated" => format!("^{ann} {form}"),
                    _ => format!("`^{ann} {form}"),
                };
                // A fresh namespace per row over one shared runtime: an
                // annotation that defines or mutates something must not leak
                // into the next row's answer, and what a row can define is a
                // var, which is what a namespace holds. Building a runtime per
                // row instead cost this suite 49 of the suite's 193 seconds.
                let (_g, mut env) = make_env(cljrs_runtime::ExecutionMode::TreeWalk);
                let got = outcome(&mut env, &format!("(meta {expr})"));
                out.push_str(&format!("{position} | (meta {expr}) => {got}\n"));
            }
            out.push('\n');
        }
    }

    // The value itself, not just its metadata: an annotation must be invisible
    // to everything except `meta`.
    out.push_str("## value-is-unchanged\n\n");
    for &form in FORMS {
        let (_g, mut env) = make_env(cljrs_runtime::ExecutionMode::TreeWalk);
        let annotated = outcome(&mut env, &format!("(pr-str ^{{:a 1}} {form})"));
        let bare = outcome(&mut env, &format!("(pr-str {form})"));
        out.push_str(&format!(
            "value | ^{{:a 1}} {form} => {annotated} | bare => {bare}\n"
        ));
    }
    out.push('\n');

    // Every row again, this time through the IR tier. A divergence between the
    // two blocks is the defect this whole change was about.
    cljrs_runtime::tiered::force_eager_lowering();
    for &(label, prefix) in &[("evaluated", "^"), ("quoted", "'^")] {
        out.push_str(&format!("## tier-parity ({label} position, IR tier)\n\n"));
        for &ann in ANNOTATIONS {
            for &form in FORMS {
                let (_g, mut env) = make_env(cljrs_runtime::ExecutionMode::Tiered);
                let got = outcome(
                    &mut env,
                    &format!("(defn probe [] (meta {prefix}{ann} {form})) (probe)"),
                );
                out.push_str(&format!(
                    "ir-{label} | (meta {prefix}{ann} {form}) => {got}\n"
                ));
            }
            out.push('\n');
        }
    }

    out
}

#[test]
fn behaviour_matches_the_golden_record() {
    let rendered = render();

    if std::env::var("UPDATE_GOLDEN").is_ok() {
        std::fs::create_dir_all(std::path::Path::new(GOLDEN).parent().unwrap()).unwrap();
        std::fs::write(GOLDEN, &rendered).unwrap();
        eprintln!("golden record updated: {GOLDEN}");
        return;
    }

    let expected = std::fs::read_to_string(GOLDEN).unwrap_or_else(|e| {
        panic!("cannot read {GOLDEN}: {e}\nrun with UPDATE_GOLDEN=1 to create it")
    });

    if rendered != expected {
        let diff: Vec<String> = expected
            .lines()
            .zip(rendered.lines())
            .filter(|(a, b)| a != b)
            .take(20)
            .map(|(a, b)| format!("  - {a}\n  + {b}"))
            .collect();
        panic!(
            "behaviour changed against the golden record ({} of {} lines differ):\n{}\n\n\
             If the change is intended, regenerate with UPDATE_GOLDEN=1 and justify \
             every changed row in the diff.",
            expected
                .lines()
                .zip(rendered.lines())
                .filter(|(a, b)| a != b)
                .count(),
            expected.lines().count(),
            diff.join("\n")
        );
    }
}

/// The two tier blocks must agree row for row — the golden file records the
/// agreement, this asserts it, so a future regeneration cannot quietly bless a
/// divergence.
#[test]
fn the_two_tiers_agree_row_for_row() {
    let rendered = render();
    for (position, ir_prefix) in [
        ("evaluated | (meta ", "ir-evaluated | (meta "),
        ("quoted | (meta ", "ir-quoted | (meta "),
    ] {
        let walked: Vec<&str> = rendered
            .lines()
            .filter_map(|l| l.strip_prefix(position))
            .collect();
        let lowered: Vec<&str> = rendered
            .lines()
            .filter_map(|l| l.strip_prefix(ir_prefix))
            .collect();

        assert!(!walked.is_empty(), "no `{position}` rows rendered");
        assert_eq!(
            walked.len(),
            lowered.len(),
            "the two `{position}` tier blocks cover a different number of cases"
        );
        for (w, l) in walked.iter().zip(&lowered) {
            assert_eq!(w, l, "a `{position}` row differs between the tiers");
        }
    }
}
